
# Streamlit Cloud에 저장할 Secrets 정보 예시
# https://docs.streamlit.io/deploy/streamlit-community-cloud/deploy-your-app/secrets-management

# jsonbin.io API Key
JSONBIN_API_KEY = "YOUR_JSONBIN_API_KEY"

# jsonbin.io Bin ID
JSONBIN_BIN_ID = "YOUR_JSONBIN_BIN_ID"
